apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: argocd

patches:
- path: resource-limits.yaml

configMapGenerator:
- name: argocd-cm
  behavior: merge
  literals:
  - timeout.reconciliation=120s
  - exec.enabled=false
  - server.insecure=false
