apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: dev-cluster
  region: ap-southeast-1
  version: "1.28"
  tags:
    Environment: dev
    ManagedBy: eksctl
    CostCenter: development
    Owner: platform-team

vpc:
  cidr: "10.0.0.0/16"
  nat:
    gateway: Single
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
  subnets:
    private:
      ap-southeast-1a:
        id: subnet-1234567a
        cidr: "10.0.1.0/24"
      ap-southeast-1b:
        id: subnet-1234567b
        cidr: "10.0.2.0/24"
    public:
      ap-southeast-1a:
        id: subnet-8901234a
        cidr: "10.0.3.0/24"
      ap-southeast-1b:
        id: subnet-8901234b
        cidr: "10.0.4.0/24"

managedNodeGroups:
  - name: ng-system
    instanceType: t3.medium
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 50
    volumeType: gp3
    privateNetworking: true
    labels:
      workload-type: system
    taints:
      - key: CriticalWorkload
        value: "true"
        effect: NoSchedule
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        albIngress: true
        ebs: true

  - name: ng-apps
    instanceType: t3.small
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    volumeSize: 30
    volumeType: gp3
    privateNetworking: true
    labels:
      workload-type: application
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true

addons:
  - name: vpc-cni
    version: latest
    configurationValues: |
      enableNetworkPolicy: true
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
  - name: metrics-server
    version: latest

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]

secretsEncryption:
  keyARN: arn:aws:kms:ap-southeast-1:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab
