apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # General Configurations
  url: https://argocd.yourdomain.com  # Replace with your actual domain
  application.instanceLabelKey: argocd.argoproj.io/instance
  admin.enabled: "false"  # Disable local admin for SSO usage
  timeout.reconciliation: 180s
  
  # Repository configurations
  repositories: |
    - type: git
      url: https://github.com/lethanhson9901/cm.git
      name: cluster-config
      
  # Resource customizations
  resource.customizations: |
    networking.k8s.io/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "Ingress is healthy"
        return hs
    apps/Deployment:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.availableReplicas ~= nil and obj.status.availableReplicas > 0 then
            hs.status = "Healthy"
            hs.message = "Deployment is healthy"
            return hs
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for rollout"
        return hs

  # RBAC Configuration
  policy.default: role:readonly
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, *, *, allow
    p, role:org-admin, repositories, *, *, allow
    p, role:org-admin, logs, *, *, allow
    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, sync, */*, allow
    p, role:developer, logs, get, */*, allow
