apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  # Webhook configurations for GitHub
  webhook.github.secret: ${GITHUB_WEBHOOK_SECRET}
  # DO NOT commit actual secrets - use secret management like AWS Secrets Manager or HashiCorp Vault
