apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.3/manifests/install.yaml  # Use stable version
- argocd-cm.yaml
- argocd-secret.yaml
- notifications-cm.yaml

namespace: argocd

patches:
- path: patches/argocd-server-service.yaml
- path: patches/argocd-repo-server-deploy.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  environment: shared
  team: platform
