apiVersion: v1
kind: ResourceQuota
metadata:
  name: ${ENVIRONMENT}-compute-resources
  namespace: ${ENVIRONMENT}
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    requests.storage: 100Gi
    persistentvolumeclaims: "10"
