name: Deploy to AWS

on:
  push:
    branches: [ main ]
    paths:
      - 'platforms/aws/**'
      - 'apps/**'
      - 'environments/aws/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: app-source
  TF_VERSION: 1.0.0

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: platforms/aws/terraform

      - name: Terraform Validate
        run: |
          terraform init -backend=false
          terraform validate
        working-directory: platforms/aws/terraform

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    environment: aws-prod
    
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Infrastructure
        working-directory: platforms/aws
        run: |
          ./scripts/deploy.sh prod
        env:
          TF_VAR_environment: prod
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
