name: GitOps Integration Tests
on:
  pull_request:
    paths:
      - 'clusters/**'
      - 'platform/**'
      - 'applications/**'
jobs:
  validate-manifests:
    name: Validate K8s Manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.9.3
        with:
          kubectl: '1.28.2'
          kustomize: '5.1.1'
          kubeconform: '0.6.3'
      - name: Validate Kubernetes manifests
        run: |
          find . -type f -name "*.yaml" -not -path "./infrastructure/*" | \
          while read file; do
            echo "Validating $file"
            kubeconform -strict -ignore-missing-schemas "$file"
          done
      - name: Verify Kustomize builds
        run: |
          for env in dev staging prod; do
            if [ -d "applications/overlays/$env" ]; then
              echo "Verifying kustomize build for $env"
              kustomize build "applications/overlays/$env"
            fi
          done
