name: Terraform Validation
on:
  pull_request:
    paths:
      - 'infrastructure/terraform/**'
      - '.github/workflows/terraform.yaml'
jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Terraform Format Check
        run: |
          cd infrastructure/terraform
          terraform fmt -check -recursive
      - name: Terraform Init
        run: |
          cd infrastructure/terraform/aws/environments/dev
          terraform init -backend=false
      - name: Terraform Validate
        run: |
          cd infrastructure/terraform/aws/environments/dev
          terraform validate
